version: "3.3"

services:
  c1n1:
    image: thepowerio/tpnode_evm:v0.10.1
    volumes:
      - type: bind
        source: ./c1n1.config
        target: /opt/thepower/node.config
      - type: bind
        source: ./genesis.txt
        target: /opt/thepower/genesis.txt
    ports:
      - 44001:${NODE1_API}
    expose:
      - ${NODE1_API}
      - ${NODE1_APIS}
      - ${NODE1_TPIC}
      - ${NODE1_CCPORT}

  c1n2:
    image: thepowerio/tpnode_evm:v0.10.1
    volumes:
      - type: bind
        source: ./c1n2.config
        target: /opt/thepower/node.config
      - type: bind
        source: ./genesis.txt
        target: /opt/thepower/genesis.txt
    ports:
      - 44002:${NODE2_API}
    expose:
      - ${NODE2_API}
      - ${NODE2_APIS}
      - ${NODE2_TPIC}
      - ${NODE2_CCPORT}

  c1n3:
    image: thepowerio/tpnode_evm:v0.10.1
    volumes:
      - type: bind
        source: ./c1n3.config
        target: /opt/thepower/node.config
      - type: bind
        source: ./genesis.txt
        target: /opt/thepower/genesis.txt
    ports:
      - 44003:${NODE3_API}
    expose:
      - ${NODE3_API}
      - ${NODE3_APIS}
      - ${NODE3_TPIC}
      - ${NODE3_CCPORT}

