version: "3.3"

services:
  c1n1:
    restart: unless-stopped
    image: ${IMAGE}
    volumes:
      - type: bind
        source: ./c1n1.config
        target: /opt/thepower/node.config
      - type: bind
        source: ./genesis.txt
        target: /opt/thepower/genesis.txt
      - type: bind
        source: ./db
        target: /opt/thepower/db
      - type: bind
        source: ./log_c1n1
        target: /opt/thepower/log
    ports:
      - 44001:${NODE1_API}
    expose:
      - ${NODE1_API}
      - ${NODE1_APIS}
      - ${NODE1_TPIC}
      - ${NODE1_CCPORT}

  c1n2:
    restart: unless-stopped
    image: ${IMAGE}
    volumes:
      - type: bind
        source: ./c1n2.config
        target: /opt/thepower/node.config
      - type: bind
        source: ./genesis.txt
        target: /opt/thepower/genesis.txt
      - type: bind
        source: ./db
        target: /opt/thepower/db
      - type: bind
        source: ./log_c1n2
        target: /opt/thepower/log
    ports:
      - 44002:${NODE2_API}
    expose:
      - ${NODE2_API}
      - ${NODE2_APIS}
      - ${NODE2_TPIC}
      - ${NODE2_CCPORT}

  c1n3:
    restart: unless-stopped
    image: ${IMAGE}
    volumes:
      - type: bind
        source: ./c1n3.config
        target: /opt/thepower/node.config
      - type: bind
        source: ./genesis.txt
        target: /opt/thepower/genesis.txt
      - type: bind
        source: ./db
        target: /opt/thepower/db
      - type: bind
        source: ./log_c1n3
        target: /opt/thepower/log
    ports:
      - 44003:${NODE3_API}
    expose:
      - ${NODE3_API}
      - ${NODE3_APIS}
      - ${NODE3_TPIC}
      - ${NODE3_CCPORT}

